version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contabilita-app
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Server=192.168.1.220;Port=3306;Database=ContabilitaDb;User=maestrale;Password=myLongAndStrongPassword24!;
      - Jwt__Key=YourSuperSecretKeyThatIsAtLeast32CharactersLongForProduction!
      - Jwt__Issuer=ContabilitaAPI
      - Jwt__Audience=ContabilitaApp
    ports:
      - "8080:80"

networks:
  contabilita-network:
    driver: bridge
